################################ 
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
################################
Module: opm-material
Description: This module contains the thermodynamic framework used by OPM
Version: 2.0
Label: 2013.10
Url: http://opm-project.org
Maintainer: and@poware.org
MaintainerName: Andreas Lauser
Depends: dune-common opm-core
