####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-material
Description: This module contains the thermodynamic framework used by OPM
Version: 2016.10.0-rc1
Label: 2016.10.0-rc1
Maintainer: opm@opm-project.org
MaintainerName: The Open Porous Media Project
Url: http://opm-project.org
Depends: dune-common opm-common
Suggests: opm-parser
